In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
from scipy.stats import ttest_ind

In [43]:
df_crime_rate = pd.read_csv('data/Crime_rate_1960-2019.csv')
df_crime_rate = df_crime_rate.drop(['Unnamed: 1','Unnamed: 2'],axis=1)
df_crime_rate

,Year,Population,Total,Violent,Property,Murder,Forcible Rape,Robbery,Aggravated assault,Burglary,Larceny Theft,Vehicle Theft
0,1960,"179,323,175","1,887.2",160.9,"1,726.3",5.1,9.6,60.1,86.1,508.6,"1,034.7",183.0
1,1961,"182,992,000","1,906.1",158.1,"1,747.9",4.8,9.4,58.3,85.7,518.9,"1,045.4",183.6
2,1962,"185,771,000","2,019.8",162.3,"1,857.5",4.6,9.4,59.7,88.6,535.2,"1,124.8",197.4
3,1963,"188,483,000","2,180.3",168.2,"2,012.1",4.6,9.4,61.8,92.4,576.4,"1,219.1",216.6
4,1964,"191,141,000","2,388.1",190.6,"2,197.5",4.9,11.2,68.2,106.2,634.7,"1,315.5",247.4
5,1965,"193,526,000","2,449.0",200.2,"2,248.8",5.1,12.1,71.7,111.3,662.7,"1,329.30",256.8
6,1966,"195,576,000","2,670.8",220.0,"2,450.9",5.6,13.2,80.8,120.3,721.0,"1,442.9",286.9
7,1967,"197,457,000","2,989.7",253.2,"2,736.5",6.2,14.0,102.8,130.2,826.6,"1,575.8",334.1
8,1968,"199,399,000","3,370.2",298.4,"3,071.8",6.9,15.9,131.8,143.8,932.3,"1,746.6",393.0
9,1969,"201,385,000","3,680.0",328.7,"3,351.3",7.3,18.5,148.4,154.5,984.1,"1,930.9",436.2
10,1970,"203,235,298","3,984.5",363.5,"3,621.0",7.9,18.7,172.1,164.8,"1,084.9","2,079.3",456.8
11,1971,"206,212,000","4,164.7",396.0,"3,768.8",8.6,20.5,188.0,178.8,"1,163.5","2,145.5",459.8
12,1972,"208,230,000","3,961.4",401.0,"3,560.4",9.0,22.5,180.7,188.8,"1,140.8","1,993.6",426.1
13,1973,"209,851,000","4,154.4",417.4,"3,737.0",9.4,24.5,183.1,200.5,"1,222.5","2,071.9",442.6
14,1974,"211,392,000","4,850.4",461.1,"4,389.3",9.8,26.2,209.3,215.8,"1,437.7","2,489.5",462.2
15,1975,"213,124,000","5,298.5",487.8,"4,810.7",9.6,26.3,220.8,231.1,"1,532.1","2,804.8",473.7
16,1976,"214,659,000","5,287.3",467.8,"4,819.5",8.7,26.6,199.3,233.2,"1,448.2","2,921.3",450.0
17,1977,"216,332,000","5,077.6",475.9,"4,601.7",8.8,29.4,190.7,247.0,"1,419.8","2,729.9",451.9
18,1978,"218,059,000","5,140.4",497.8,"4,642.5",9.0,31.0,195.8,262.1,"1,434.6","2,747.4",460.5
19,1979,"220,099,000","5,565.5",548.9,"5,016.6",9.8,34.7,218.4,286.0,"1,511.9","2,999.1",505.6
20,1980,"225,349,264","5,950.0",596.6,"5,353.3",10.2,36.8,251.1,298.5,"1,684.1","3,167.0",502.2
21,1981,"229,146,000","5,858.2",594.3,"5,263.8",9.8,36.0,258.7,289.7,"1,649.5","3,139.7",474.7
22,1982,"231,534,000","5,603.7",571.1,"5,032.5",9.1,34.0,238.9,289.1,"1,488.8","3,084.9",458.9
23,1983,"233,981,000","5,175.0",537.7,"4,637.3",8.3,33.7,216.5,279.2,"1,337.7","2,869.0",430.8
24,1984,"236,158,000","5,031.3",539.2,"4,492.1",7.9,35.7,205.4,290.2,"1,263.7","2,791.3",437.1
25,1985,"238,740,000","5,207.1",556.6,"4,650.5",8.0,37.1,208.5,302.9,"1,287.3","2,901.2",462.0
26,1986,"240,132,887","5,480.4",620.1,"4,881.8",8.6,38.1,226.0,347.4,"1,349.8","3,022.1",509.8
27,1987,"242,288,918","5,550.0",609.7,"4,940.3",8.3,37.4,212.7,351.3,"1,329.60","3,081.3",529.5
28,1988,"245,807,000","5,664.2",637.2,"5,027.1",8.4,37.6,220.9,370.2,"1,309.2","3,134.9",582.9
29,1989,"248,239,000","5,741.0",663.1,"5,077.9",8.7,38.1,233.0,383.4,"1,276.3","3,171.3",630.4
30,1990,"248,709,873","5,820.3",731.8,"5,088.5",9.4,41.2,257.0,424.1,"1,235.9","3,194.8",657.8
31,1991,"252,177,000","5,897.8",758.1,"5,139.7",9.8,42.3,272.7,433.3,"1,252.0","3,228.8",658.9
32,1992,"255,082,000","5,660.2",757.5,"4,902.7",9.3,42.8,263.6,441.8,"1,168.2","3,103.0",631.5
33,1993,"257,908,000","5,484.4",746.8,"4,737.7",9.5,41.1,255.9,440.3,"1,099.2","3,032.4",606.1
34,1994,"260,341,000","5,373.5",713.6,"4,660.0",9.0,39.3,237.7,427.6,"1,042.0","3,026.7",591.3
35,1995,"262,755,000","5,274.9",684.5,"4,591.3",8.2,37.1,220.9,418.3,987.1,"3,043.8",560.4
36,1996,"265,284,000","5,087.6",636.6,"4,451.0",7.4,36.3,201.9,390.9,945.0,"2,980.3",525.7
37,1997,"267,637,000","4,927.3",611.0,"4,316.3",6.8,35.9,186.1,382.1,919.6,"2,891.8",505.7
38,1998,"270,296,000","4,615.5",566.4,"4,049.1",6.3,34.4,165.2,360.5,862.0,"2,728.1",459.0
39,1999,"272,690,813","4,266.5",523,"3,743.6",5.7,32.8,150.1,334.3,770.4,"2,550.7",422.5
40,2000,"281,421,906","4,124.80",506.5,"3,618.3",5.5,32,145,324.0,728.8,"2,477.30",412.2
41,2001,"285,317,559","4,162.60",504.5,"3,658.1",5.6,31.8,148.5,318.6,741.8,"2,485.7",430.5
42,2002,"287,973,924","4,125.00",494.4,"3,630.6",5.6,33.1,146.1,309.5,747.0,"2,450.7",432.9
43,2003,"290,690,788","4,067.00",475.8,"3,591.20",5.7,32.3,142.5,295.4,741.0,"2,416.50",433.7
44,2004,"293,656,842","3,977.30",463.2,"3,514.1",5.5,32.4,136.7,288.6,730.3,"2,362.3",421.5
45,2005,"296,507,061","3,900.50",469.0,"3,431.5",5.6,31.8,140.8,290.8,726.9,"2,287.8",416.8
46,2006,"299,398,484","3,808.10",473.6,"3,334.5",5.7,30.9,149.4,287.5,729.4,"2,206.8",398.4
47,2007,"301,621,157","3,730.40",466.9,"3,263.5",5.6,30,147.6,283.8,722.5,"2,177.8",363.3
48,2008,"304,374,846","3,669.00",457.5,"3,211.5",5.4,29.7,145.7,276.7,732.1,"2,167.0",314.7
49,2009,"307,006,550","3,465.50",431.9,"3,036.1",5.0,29.1,133.1,264.7,717.7,"2,064.5",259.2
50,2010,"309,330,219","3,350.40",404.5,"2,945.90",4.8,27.7,119.3,252.8,701,"2,005.80",239.1
51,2011,"311,587,816","3,292.50",387.1,"2,905.40",4.7,27,113.9,241.5,701.3,"1,974.10",230
52,2012,"313,873,685","3,255.80",387.8,"2,868.00",4.7,27.1,113.1,242.8,672.2,"1,965.40",230.4
53,2013,"316,497,531","3,112.40",379.1,"2,733.30",4.5,25.9,109,229.6,610.4,"1,901.60",221.3
54,2014,"318,907,401","2,946.10",372,"2,574.10",4.4,26.6,101.3,229.2,537.2,"1,821.50",215.4
55,2015,"320,896,618","2,885.10",384.6,"2,500.50",4.9,28.4,102.2,238.1,494.7,"1,783.60",222.2
56,2016,"323,405,935","2,849.10",397.5,"2,451.60",5.4,40.9*,102.9,248.3,468.9,"1,745.40",237.3
57,2017,"325,147,121","2,757.80",394.9,"2,362.90",5.3,41.7,98.6,249.2,429.7,"1,695.50",237.7
58,2018,"326,687,501","2,593.2",383.4,"2,209.8",5.0,44.0,86.1,248.2,378.0,"1,601.6",230.2
59,2019,"328,239,523","2,489.3",379.4,"2,109.9",5.0,42.6,81.6,250.2,340.5,"1,549.5",219.9

In [33]:
df_inflation = pd.read_csv('data/US_inflation_rates.csv')
df_inflation

           date    value
0    1947-01-01   21.480
1    1947-02-01   21.620
2    1947-03-01   22.000
3    1947-04-01   22.000
4    1947-05-01   21.950
..          ...      ...
913  2023-02-01  301.648
914  2023-03-01  301.808
915  2023-04-01  302.918
916  2023-05-01  303.294
917  2023-06-01  303.841

[918 rows x 2 columns]

In [34]:
df_population = pd.read_csv('data/united-states-population-2023-11-16.csv')
df_population # i dont know if this data is neccessary or not because we may need to use the change rate of the poulation

           date  Population  Annual % Change
0    1950-12-31   148281550              NaN
1    1951-12-31   150598453             1.56
2    1952-12-31   152941727             1.56
3    1953-12-31   155451199             1.64
4    1954-12-31   158205873             1.77
..          ...         ...              ...
146  2096-12-31   393602753             0.03
147  2097-12-31   393728779             0.03
148  2098-12-31   393843026             0.03
149  2099-12-31   393946323             0.03
150  2100-12-31   394041155             0.02

[151 rows x 3 columns]